alarm_definitions = {
    (50000, 3): {'alarm_id': 1100, 'alarm_name': 'Abnormal Active Schedule', 'severity': 'Major'},
    (50000, 4): {'alarm_id': 1100, 'alarm_name': 'Abnormal Active Schedule', 'severity': 'Major'},
    (50000, 11): {'alarm_id': 1101, 'alarm_name': 'Abnormal Reactive Schedule', 'severity': 'Major'},
    (50000, 12): {'alarm_id': 1101, 'alarm_name': 'Abnormal Reactive Schedule', 'severity': 'Major'},
    (50001, 1): {'alarm_id': 1103, 'alarm_name': 'MCB Disconnect', 'severity': 'Major'},
    (50001, 2): {'alarm_id': 1104, 'alarm_name': 'Abnormal Cubicle', 'severity': 'Major'},
    (50001, 3): {'alarm_id': 1105, 'alarm_name': 'Device Address Conflict', 'severity': 'Major'},
    (50001, 4): {'alarm_id': 1106, 'alarm_name': 'AC SPD fault', 'severity': 'Major'},
    (50001, 5): {'alarm_id': 1107, 'alarm_name': 'DI1 custom alarm', 'severity': 'Adaptable'},
    (50001, 13): {'alarm_id': 1115, 'alarm_name': '24V power failure', 'severity': 'Major'},
    (50002, 0): {'alarm_id': 1116, 'alarm_name': 'WebUI server certificate invalid', 'severity': 'Warning'},
    (50002, 1): {'alarm_id': 1117, 'alarm_name': 'WebUI server certificate to expire', 'severity': 'Warning'},
    (50002, 2): {'alarm_id': 1118, 'alarm_name': 'WebUI server certificate expired', 'severity': 'Major'},
    (50001, 14): {'alarm_id': 1119, 'alarm_name': 'License Expired', 'severity': 'Warning'},
    (50002, 3): {'alarm_id': 1120, 'alarm_name': 'Management system certificate invalid', 'severity': 'Warning'},
    (50002, 4): {'alarm_id': 1121, 'alarm_name': 'Management System Certificate to Expire', 'severity': 'Warning'},
    (50002, 6): {'alarm_id': 1123, 'alarm_name': 'Remote Control Certificate invalid', 'severity': 'Warning'},
    (50003, 5): {'alarm_id': 1120, 'alarm_name': 'Management System Certificate Invalid', 'severity': 'Warning'},
    (50003, 0): {'alarm_id': 1120, 'alarm_name': 'Management System Certificate Invalid', 'severity': 'Warning'},
    (50003, 1): {'alarm_id': 1121, 'alarm_name': 'Management System Certificate to Expire', 'severity': 'Warning'},
    (50003, 2): {'alarm_id': 1122, 'alarm_name': 'Management System Certificate Expired', 'severity': 'Major'},
    (50002, 5): {'alarm_id': 1122, 'alarm_name': 'Management System Certificate Expired', 'severity': 'Major'},
    (50002, 7): {'alarm_id': 1124, 'alarm_name': 'Remote Control Certificate to expire', 'severity': 'Warning'},
    (50002, 8): {'alarm_id': 1125, 'alarm_name': 'Remote Control Certificate expired', 'severity': 'Major'},
    (50002, 9): {'alarm_id': 1126, 'alarm_name': 'ESGCC Certificate invalid', 'severity': 'Warning'},
    (50002, 10): {'alarm_id': 1127, 'alarm_name': 'ESGCC Certificate to expire', 'severity': 'Warning'},
    (50002, 11): {'alarm_id': 1128, 'alarm_name': 'ESGCC Certificate expired', 'severity': 'Major'},
    (50002, 12): {'alarm_id': 1129, 'alarm_name': 'SmartLog ger Certificate Invalid', 'severity': 'Warning'},
    (50002, 13): {'alarm_id': 1130, 'alarm_name': 'SmartLog ger Certificate About to Expire', 'severity': 'Warning'},
    (50002, 14): {'alarm_id': 1131, 'alarm_name': 'SmartLog ger Certificate Expired', 'severity': 'Major'},
    (50002, 15): {'alarm_id': 1132, 'alarm_name': 'One or Two Smart Rack Controller Cables Not Connecte d to DC Bus', 'severity': 'Major'},
    (50004, 0): {'alarm_id': 1133, 'alarm_name': 'Smart Tracker Out of Control', 'severity': 'Major'},
    (50003, 3): {'alarm_id': 1134, 'alarm_name': 'One or Two Smart PCS Cables Not Connecte d to DC Bus', 'severity': 'Major'},
    (50004, 1): {'alarm_id': 1135, 'alarm_name': 'Insufficie nt SDS License Capacity', 'severity': 'Major'},
    (50005, 0): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 1): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 2): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 3): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 4): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 5): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 6): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 7): {'alarm_id': 1140, 'alarm_name': 'Array Black Start Failed', 'severity': 'Minor'},
    (50005, 8): {'alarm_id': 1141, 'alarm_name': 'The STS is switched off, and the ESS shutdown protection is triggered.', 'severity': 'Major'},
    (50005, 13): {'alarm_id': 1142, 'alarm_name': 'Switch Control Failed at Grid Connection Point', 'severity': 'Major'},
    (50005, 14): {'alarm_id': 1143, 'alarm_name': 'The system-to-ground insulation capability of the system has decreased .', 'severity': 'Major'},
    (50005, 9): {'alarm_id': 1142, 'alarm_name': 'Switch Control Failed at Grid Connection Point', 'severity': 'Major'},
    (50005, 10): {'alarm_id': 1142, 'alarm_name': 'Switch Control Failed at Grid Connection Point', 'severity': 'Major'},
    (50005, 11): {'alarm_id': 1142, 'alarm_name': 'Switch Control Failed at Grid Connection Point', 'severity': 'Major'},
    (50005, 12): {'alarm_id': 1142, 'alarm_name': 'Switch Control Failed at Grid Connection Point', 'severity': 'Major'},
    (50006, 0): {'alarm_id': 1144, 'alarm_name': 'Load Switch Control Failed', 'severity': 'Major'},
    (50006, 1): {'alarm_id': 1144, 'alarm_name': 'Load Switch Control Failed', 'severity': 'Major'},
    (50005, 15): {'alarm_id': 1145, 'alarm_name': 'Genset Control Failed', 'severity': 'Major'},
    (50006, 6): {'alarm_id': 1145, 'alarm_name': 'Genset Control Failed', 'severity': 'Major'},
    (50006, 2): {'alarm_id': 1146, 'alarm_name': 'Adjustme nt Failed During On/Off- grid Switching', 'severity': 'Major'},
    (50006, 3): {'alarm_id': 1146, 'alarm_name': 'Adjustme nt Failed During On/Off- grid Switching', 'severity': 'Major'},
    (50006, 4): {'alarm_id': 1147, 'alarm_name': 'System Black Start Failed', 'severity': 'Major'},
    (50006, 5): {'alarm_id': 1148, 'alarm_name': 'Array fault shutdown', 'severity': 'Major'},
    (50006, 9): {'alarm_id': 1149, 'alarm_name': 'The temperat ure inside the communi cations cabinet is too high.', 'severity': 'Minor'},
    (50006, 7): {'alarm_id': 1150, 'alarm_name': 'Power Control Abnormal at Grid Connection Point', 'severity': 'Major'},
    (50006, 8): {'alarm_id': 1152, 'alarm_name': 'ESS Control Abnormal', 'severity': 'Major'},
    (50006, 10): {'alarm_id': 1160, 'alarm_name': 'Expansion module software version mismatch', 'severity': 'Warning'},
    (50006, 11): {'alarm_id': 1161, 'alarm_name': 'Battery cluster input test failed', 'severity': 'Major'},
    (50006, 12): {'alarm_id': 1162, 'alarm_name': 'Battery cluster Fast IO test failed', 'severity': 'Major'},
}