name: Deploy to Production
on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/webapp_backend
  IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/webapp_frontend
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:${{ env.TAG }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_WEBAPP_SERVER_HOST }}
          username: ${{ secrets.PROD_WEBAPP_USER }}
          port: ${{ secrets.PROD_WEBAPP_SERVER_PORT }}
          key: ${{ secrets.PROD_WEBAPP_SSH_KEY }}
          script: |
            set -e
            docker login ${{ env.REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ env.IMAGE_BACKEND }}:${{ env.TAG }}
            docker pull ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}
            docker rm -f webapp_backend || true
            docker rm -f webapp_frontend || true
            docker run -d --name webapp_backend --restart=always \
              -p 8000:8000 \
              ${{ env.IMAGE_BACKEND }}:${{ env.TAG }} \
              uvicorn main:app --host 0.0.0.0 --port 8000
            docker run -d --name webapp_frontend --restart=always \
              -p 3000:80 \
              ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}
            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"
